### ISSUE TITLE
Week 9 Exercise

### ISSUE THREAD

**Issue by billyJoePiano** [billyJoePiano/TenaPull#8]
@pawaitemadisoncollege

I have a RESTful service functioning now with the indy project!  Screenshots in the screenshots directory

I was a little confused at first about the way to deploy this, but got it working using Tomcat after a little trial and error.  I'm wondering if there are any particular advantages to TomEE over Tomcat, and if there's any instructions you'd suggest about deploying with TomEE instead?  I noticed in some of the things I found on google there were mentions of Jakarta... would that change the type of server we'd need to use?

Thanks,

Bill

**Comment by pawaitemadisoncollege** [comment]
Hey @billyJoePiano,

- The deploy for this is the same as any of the other web applications that we've been working with this semester. Any web application that runs on Tomcat will be deployed the same way. 
- TomEE includes some of the JavaEE bits; we'll use TomEE for the week 13 exercise which involves Message Driven Beans (MDBs).  Setting up TomEE is no different from Tomcat really - it'll just be a matter of downloading and unzipping just like we did to set up Tomcat in week 1.
- Thorough job with error handling in the scan service!
